# !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
# !!!!!!!!!!!!!! This repository is public !!!!!!!!!!!!!!!!!!!!!!!!
# !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

# repo is public until Github Action supports cloning private repos
# https://github.com/github/roadmap/issues/74
name: 'Get Git SHA for PR or Branch Build'
description: 'Get Git SHA for PR or Branch Build'
inputs:
  github_sha:
    description: 'should be github.sha'
    required: true
  github_event_pull_request_head_sha:
    description: 'should be github.event.pull_request.head.sha'
    required: true
  github_event_number:
    description: 'should be github.event.number'
    required: true
  github_event_pull_request_base_ref:
    description: 'should be github.event.pull_request.base.ref'
    required: true
  github_event_ref:
    description: 'should be github.event.ref'
    required: true
  github_head_ref:
    description: 'should be github.head_ref'
    required: true
  github_ref:
    description: 'should be github.ref'
    required: true
outputs:
  sha:
    description: "if pull request : 'github.event.pull_request.head.sha' else : 'github.sha'"
    value: ${{ steps.do.outputs.sha }}
  isPullRequest:
    description: "'true' or 'false'"
    value: ${{ steps.do.outputs.isPullRequest }}
  uniqueName:
    description: "if pull request: 'inputs.github_event_number' else : short 'github.sha' "
    value: ${{ steps.do.outputs.uniqueName }}
  baseBranch:
    description: "if pull request: 'github.event.pull_request.base.ref' else : short 'github.event.ref' stripped out of 'refs/heads/' "
    value: ${{ steps.do.outputs.baseBranch }}
  currentBranch:
    description: "if pull request: 'github.event.pull_request.base.ref' else : short 'github.event.ref' stripped out of 'refs/heads/' "
    value: ${{ steps.do.outputs.currentBranch }}
runs:
  using: "composite"
  steps:
    - shell: bash
      id: do
      run: |
        if [[ "${{ inputs.github_event_pull_request_head_sha }}" != "" ]]; then
          sha=${{ inputs.github_event_pull_request_head_sha  }}
          isPullRequest="true"
          uniqueName="${{ inputs.github_event_number }}"
          baseBranch=${{ inputs.github_event_pull_request_base_ref }}
          currentBranch=${{ inputs.github_head_ref }}
          currentBranch=${currentBranch:0:10}
          # replace "/" with "-", to avoid errors from validators
          currentBranch=${currentBranch//\//-}
          # replace "_" with "-", to avoid errors from validators
          currentBranch=${currentBranch//_/-}
          # replace "." with "-", to avoid errors from validators
          currentBranch=${currentBranch//\./-}
        else
          sha=${{ inputs.github_sha }}
          isPullRequest="false"
          uniqueName=${sha:0:8}
          baseBranch=${{ inputs.github_event_ref }}
          baseBranch=${baseBranch#refs/heads/}
          currentBranch=${{ inputs.github_ref }}
          currentBranch=${currentBranch#refs/heads/}
        fi
        currentBranch=$(echo ${currentBranch} | tr "[:upper:]" "[:lower:]")
        
        echo "sha : ${sha}"
        echo "uniqueName : ${uniqueName}"
        echo "isPullRequest : ${isPullRequest}"
        echo "currentBranch : ${currentBranch}"

        echo "::set-output name=sha::${sha}"
        echo "::set-output name=isPullRequest::${isPullRequest}"
        echo "::set-output name=uniqueName::${uniqueName}"
        echo "::set-output name=baseBranch::${baseBranch}"
        echo "::set-output name=currentBranch::${currentBranch}"
